POST http://localhost:3001/api/users 
Content-Type: application/json

{
  "email": "roott@root.com", 
  "name": "rootname", 
  "surname": "rootsur", 
  "password": "root"
}

###
GET http://localhost:3001/api/users 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxYTA3Mjc5NWQ0MGQ1YTE2NDc2ZmRmMCIsImlhdCI6MTYzNzkwNTAyOCwiZXhwIjoxNjM3OTA4NjI4fQ.XGaXAk1LRM8qSEKhv2cqUFTKO2BWw5PAd0N-RREe138


###
POST http://localhost:3001/api/login 
Content-Type: application/json 

{
  "email": "roott@root.com", 
  "password": "root"
}

###
PUT http://localhost:3001/api/Users 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWE1YTIwNzRhMGFmZmI4YzgzZDQzOTMiLCJpYXQiOjE2MzgyNDQ4NzYsImV4cCI6MTYzODI0ODQ3Nn0.Hvke5tT2SiimZRcDv6Kl5jRLK20Q7IauM6WEoxBV_cA

{
  "currentPassword": "root",
  "newPassword": "root2"
}

###
POST http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWE1OTdhMzlmZGYyOWY1ZDUwMjQ1NDkiLCJpYXQiOjE2MzgyNDIyNTQsImV4cCI6MTYzODI0NTg1NH0.tnSscvHRFD8qsI8CrqdtwK29RUxqumBLOlrOAUX_AGQ

###
PUT http://localhost:3001/api/decks/61a16713731fce3b3ea66758
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWExNjZmZTczMWZjZTNiM2VhNjY3NTQiLCJpYXQiOjE2Mzc5ODA2NTYsImV4cCI6MTYzNzk4NDI1Nn0.xNs-uYxBnk616stdqPiAWyPKqReuVwK0ZIYUuC4nZkA

{
  "title": "newTitle"
}

###
GET http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWE1Njg1MDg0OTNlYmMyYTgwZmFkZDIiLCJpYXQiOjE2MzgyMzAwOTgsImV4cCI6MTYzODIzMzY5OH0.bv62ijcEU65PF-qznhWo9cXPc_fd5ItMLoM_VWDKLEU

###
DELETE http://localhost:3001/api/decks/61a07765137ed1086eb3fade
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxYTA3Mjc5NWQ0MGQ1YTE2NDc2ZmRmMCIsImlhdCI6MTYzNzk2NTY1OCwiZXhwIjoxNjM3OTY5MjU4fQ.GhMNfUGHaN1uoPHDz-WKIFa32919EocAtCx3rZNZShE

###
GET http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxODlmZTcyMmY3ZTI4Njk1YWU2ZmQ2YSIsImlhdCI6MTYzNjY4MTI0MSwiZXhwIjoxNjM2Njg0ODQxfQ.C3pRhGBlUFkf-vzHgwNVghJVRhdII8T7jc4W7K1w9xo

###
POST http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWE1OTdhMzlmZGYyOWY1ZDUwMjQ1NDkiLCJpYXQiOjE2MzgyNDIyNTQsImV4cCI6MTYzODI0NTg1NH0.tnSscvHRFD8qsI8CrqdtwK29RUxqumBLOlrOAUX_AGQ

{
  "deckId": "61a597da9fdf29f5d502454e",
  "front": "go", 
  "back": "[]", 
  "level": 2
}

###
PUT http://localhost:3001/api/cards/6183457609ed0194358b9d45
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxYTA3Mjc5NWQ0MGQ1YTE2NDc2ZmRmMCIsImlhdCI6MTYzNzkwNTAyOCwiZXhwIjoxNjM3OTA4NjI4fQ.XGaXAk1LRM8qSEKhv2cqUFTKO2BWw5PAd0N-RREe138

{
  "front": "test", 
  "back": "[]", 
  "level": 2
}

###
DELETE http://localhost:3001/api/cards/61a597f29fdf29f5d502455f
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MWE1OTdhMzlmZGYyOWY1ZDUwMjQ1NDkiLCJpYXQiOjE2MzgyNDIyNTQsImV4cCI6MTYzODI0NTg1NH0.tnSscvHRFD8qsI8CrqdtwK29RUxqumBLOlrOAUX_AGQ