POST http://localhost:3001/api/users 
Content-Type: application/json

{
  "email": "root@root.com", 
  "name": "rootname", 
  "surname": "rootsur", 
  "password": "root"
}

###
POST http://localhost:3001/api/login 
Content-Type: application/json 

{
  "email": "roott@root.com", 
  "password": "root"
}

###
PUT http://localhost:3001/api/Users 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3R0QHJvb3QuY29tIiwiaWQiOiI2MThlMmM5M2JhYzRjMmY1MmMwOGM5YTMiLCJpYXQiOjE2MzY3MDc0ODUsImV4cCI6MTYzNjcxMTA4NX0.0U2YsxHFz2AlMN5qeTOKuxe6Y34QVZU6SHGiWcvmDHA

{
  "email": "b@b",
  "newPassword": "rootroot",
  "currentPassword": "root"
}

###
GET http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxODlmZTcyMmY3ZTI4Njk1YWU2ZmQ2YSIsImlhdCI6MTYzNjY4MTI0MSwiZXhwIjoxNjM2Njg0ODQxfQ.C3pRhGBlUFkf-vzHgwNVghJVRhdII8T7jc4W7K1w9xo

###
POST http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxODlmZTcyMmY3ZTI4Njk1YWU2ZmQ2YSIsImlhdCI6MTYzNjY4MTI0MSwiZXhwIjoxNjM2Njg0ODQxfQ.C3pRhGBlUFkf-vzHgwNVghJVRhdII8T7jc4W7K1w9xo

{
  "front": "go", 
  "back": "[]", 
  "level": 2
}

###
PUT http://localhost:3001/api/cards/6183457609ed0194358b9d45
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxODM0NTRlMDllZDAxOTQzNThiOWQ0MSIsImlhdCI6MTYzNTk5MjkxNCwiZXhwIjoxNjM1OTk2NTE0fQ.U374rMtZZ36AnhiDmaY6GgS66UZjBickja_a6aUNJRI

{
  "front": "test", 
  "back": "[]", 
  "level": 2
}

###
DELETE http://localhost:3001/api/cards/6183457609ed0194358b9d44
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAcm9vdC5jb20iLCJpZCI6IjYxODM0NTRlMDllZDAxOTQzNThiOWQ0MSIsImlhdCI6MTYzNTk5MjkxNCwiZXhwIjoxNjM1OTk2NTE0fQ.U374rMtZZ36AnhiDmaY6GgS66UZjBickja_a6aUNJRI